development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: social_network-development
  pool: 5
  username: root
  password: root
  socket: /opt/local/var/run/mysql5/mysqld.sock
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: social_network_test
  pool: 5
  username: root
  password: root
  socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: social_network_production
  pool: 5
  username: root
  password: root
  socket: /opt/local/var/run/mysql5/mysqld.sock